buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.install]
cmds = ["npm install -g pnpm@10.33.0", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node build"
